# Generated by Django 6.0.6 on 2026-06-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
